---
title: "p8105_hw5_mk4208"
author: "Meeraj Kothari"
date: "11/6/2019"
output: github_document
---

```{r}
library(tidyverse)
library(viridis)
library(devtools)
library(patchwork)
```


```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

Problem 1

```{r}
fill_missing = function(x) {
  if (is.numeric(x)) {
    replace_na(x, mean(x, na.rm = TRUE))
  } else if (is.character(x)) {
    replace_na(x, "virginica")
  }
}

iris_filled = map_df(iris_with_missing, fill_missing)
```

Problem 2 

```{r}
files = list.files("./data/", pattern = ".csv", full.names = TRUE)

files_df = files %>% 
  map_df(read_csv) %>% 
  mutate(filename = tools::file_path_sans_ext(basename(files))) %>%
  separate(filename, into = c("arm", "id"), convert = TRUE) %>% 
  mutate(id = row_number()) %>%
  select(id, arm, everything()) %>%
  pivot_longer(week_1:week_8,
    names_to = "week",
    values_to = "value",
    names_prefix = "week_"
  ) 

files_df %>% 
  ggplot(aes(x = week, y = value, color = arm, group = id)) +
  geom_line() + 
  theme_minimal() 
```

Problem 3 

```{r}
sim_regression = function(beta1 = 0) {
  
  sim_data = tibble(
    x = rnorm(30, mean = 0, sd = 1),
    y = 2 + beta1 * x + rnorm(30, 0, sd = 50^(1/2))
      )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta1_hat = broom::tidy(ls_fit)[2, 2] %>% as.numeric(),
    p_value = broom::tidy(ls_fit)[2, 5] %>% as.numeric()
  )

}
```


```{r}
sim_results = tibble(beta_1 = c(0, 1, 2, 3, 4, 5, 6)) %>% 
  mutate(output_lists = map(.x = beta_1, ~rerun(10000, sim_regression(beta1 = .x))),
         estimate_dfs = map(output_lists, bind_rows)) %>%
  select(-output_lists) %>%
  unnest(estimate_dfs)
```

```{r}
sim_results %>% 
  group_by(beta_1) %>%
  count(reject = p_value < 0.05) %>% 
  mutate(percent = n/sum(n)*100) %>% 
  filter(reject == TRUE) %>%
  ggplot(aes(x = beta_1, y = percent)) +
  geom_point() + 
  geom_line()
```

```{r}
p1 = sim_results %>% 
  group_by(beta_1) %>%
  summarise(mean = mean(beta1_hat)) %>% 
  ggplot(aes(x = beta_1, y = mean)) + 
  geom_point() + 
  geom_line()

p2 = sim_results %>% 
  filter(p_value < 0.05) %>% 
  group_by(beta_1) %>%
  summarise(mean = mean(beta1_hat)) %>% 
  ggplot(aes(x = beta_1, y = mean)) + 
  geom_point() +
  geom_line()

p1 + p2
```

